apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /secrets
              name: aws-secretsmanager
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "500Mi"
          envFrom:
            - secretRef:
                name: backend-secrets
      initContainers:
        - name: prepare
          image: public.ecr.aws/g3k3o5v3/baseforci
          env:
            - name: "CMD"
              value: |
                #!/bin/sh
                echo "HELLO" >> /tmp/secrets/.env
                echo "WORLD" >> /tmp/secrets/.env
          command:
            - "/bin/sh"
            - "-c"
          args:
            - 'echo "$CMD" >> command.sh && chmod +x command.sh && /bin/sh command.sh'
          volumeMounts:
            - mountPath: /tmp/secrets
              name: aws-secretsmanager
      volumes:
        - name: aws-secretsmanager
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend-secrets
  namespace: default
stringData:
  username: admin
  password: helloworld
